---
label: Project
hide_body: false
fields:
- type: file
  name: thumbnail
  label: Thumbnail
  description: This will only show up on the front page
- type: text
  name: title
  label: Title
  config:
    required: true
- type: datetime
  name: date
  label: Date
  config:
    required: true
    date_format: YYYY-MM-DD
    time_format: ''
    export_format: YYYY-MM-DD
    display_utc: true
  default: now
  hidden: true
- type: tag_list
  name: categories
  label: Categories
- type: color
  name: project_bg_color
  config:
    color_format: Hex
  label: Background color
- type: color
  name: project_fg_color
  config:
    color_format: Hex
  label: Foreground color
- name: weblink
  type: blocks
  label: weblink
  template_types:
  - enllac-web
  config:
    min: 
    max: 
- name: videos
  type: field_group
  config: {}
  fields:
  - name: title
    type: text
    config:
      required: false
    label: Title
  - name: video
    type: blocks
    label: video
    template_types: []
    config:
      min: 
      max: 
  label: videos
pages:
- projects/3d-graff.md
- projects/asteria.md
- projects/chelsea-landmark.md
- projects/ios-concept.md
- projects/sunk.md
