---
label: Project
hide_body: false
fields:
- type: file
  name: thumbnail
  label: Thumbnail
  description: This will only show up on the front page
- type: text
  name: title
  label: Title
  config:
    required: true
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
- type: datetime
  name: date
  label: Date
  config:
    required: true
    date_format: YYYY-MM-DD
    time_format: ''
    export_format: YYYY-MM-DD
    display_utc: true
  default: now
  hidden: true
- name: main_initial_video
  type: text
  config:
    required: false
  label: Main initial video
- type: tag_list
  name: categories
  label: Categories
- type: color
  name: project_bg_color
  config:
    color_format: Hex
  label: Background color
- type: color
  name: project_fg_color
  config:
    color_format: Hex
  label: Foreground color
- name: weblink
  type: blocks
  label: weblink
  template_types:
  - enllac-web
  config:
    min: 
    max: 
- name: subseccio_projecte
  type: blocks
  template_types:
  - seccio-projecte
  config:
    min: 
    max: 
  label: Subseccio projecte
- name: section
  type: blocks
  label: section
  template_types:
  - seccio-projecte
  config:
    min: 
    max: 
- name: problema
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: problema
pages:
- projects/asteria.md
- projects/cinema-palette.md
- projects/eter.md
